### ISSUE TITLE
image viewer

### ISSUE THREAD

**Issue by evanwill** [uidaholib/HJCCC_source#10]
- light gallery, https://github.com/sachinchoolur/lightGallery
- see https://github.com/ctrlshifty/ctrlshifty.github.io

**Comment by evanwill** [comment]
use cases? 

- [ ] item pages
- [ ] category gallery?

**Comment by dcnb** [comment]
it might be useful for compound objects generally ... 

(maybe that's your point)

**Comment by evanwill** [comment]
yeah-- no i was thinking beyond items pages / compound object pages--

like grab all the images for a single subject term and put them in a gallery page
