### ISSUE TITLE
glossary term pages

### ISSUE THREAD

**Issue by evanwill** [uidaholib/HJCCC_source#14]
- [x] page gen glossary 
- [x] page with definition 
- [x] browse gallery of related images

**Comment by evanwill** [comment]
a page is generated for each glossary term now from `_data/hjccc-glossary.csv`. If the "search" column is filled in, the `resources/`page term will have a link to the term page. The term page has a gallery of items created by searching the "subjects" column of `hjccc-objects.csv` using the "search" column of the glossary data. 

However, I am not sure if this data is all lining up correctly and have a few questions @RenaeCamp 

1. should the "Forms" page link to the glossary term page rather than the "Browse" page? That way users would see an definition on the form in addition to a gallery of image. However, I am not sure that the glossary data and forms data matches up exactly at this point. 

2. @RenaeCamp wanted item page metadata to link to the glossary term page, rather than to the browse page--I am having trouble doing that because there isn't a one-to-one match of the item metadata terms and the glossary terms. Is there a way to clean this up? Maybe refining the "search" column of `hjccc-glossary.csv`? Then if you told me exactly which metadata fields *might* have a glossary match, I could create a table that liquid could search to create a link to the glossary term page.

**Comment by RenaeCamp** [comment]
Yes, I like the idea of the "Forms" pages linking to the Glossary terms and gallery of images.  

I'm not sure I'm understanding the mismatch issue is with the glossary term page.  Is it that there will not be a glossary entry for each metadata field (site date, for example)? Or is it that the terms in the "search" column of the glossary are not matching up to the terms in the metadata fields?

**Comment by evanwill** [comment]
wow, i just had a Jekyll revelation, and came up with a way to do this efficiently! 

I added a field to the "metadata-fields.csv" called "glossary-search". If that is "true", when building the item pages, it checks the "hjccc-glossary.csv" "search" field to see if the metadata item matches something there, and if it does adds a link to the glossary term page. 

I think this approach and a few tweaks i did to the data fixed up the problem I was talking about...
