### ISSUE TITLE
link form tree to glossary

### ISSUE THREAD

**Issue by evanwill** [uidaholib/HJCCC_source#15]
@RenaeCamp to get the form tree viz to point to the Glossary entry, edit the [tree include](https://github.com/uidaholib/HJCCC_source/blob/master/_includes/tree.html). 

Around line 27 you will find a java script variable called "treeData", each form has a little representation in that data that looks like:

```
{
  "Category": "Tableware",
  "Type": "Bowls/Cups",
  "Form": "Chawan",
  "name": "Chawan - Yunomi (teacup)",
  "Description": "Teacups come in a  variety of sizes and range in shape from hemispherical to cylindrical (Costello et. al 2001:36).",
  "url": "{{ '/browse/#Yunomi' | relative_url }}"
}
```

Currently the "url" values point to the browse page. The stuff in the braces (i.e. `{{` and `}}`) are a [Liquid](https://shopify.github.io/liquid/) variable that helps create the correct links when we build the site. We use them so that the links will work on github, locally, and on the library web when we build it.

Could you edit each "url" value to point to the correct glossary term?

The glossary term link will look like: 

`{{ '/resources/yunomi-teacup.html' | relative_url }}`

because, all of the glossary terms are in `/resources/`, and the "slug" is in the "hjccc-glossary.csv" file, then add `.html` to the slug.

So the example above would be updated to:

```
{
  "Category": "Tableware",
  "Type": "Bowls/Cups",
  "Form": "Chawan",
  "name": "Chawan - Yunomi (teacup)",
  "Description": "Teacups come in a  variety of sizes and range in shape from hemispherical to cylindrical (Costello et. al 2001:36).",
  "url": "{{ '/resources/yunomi-teacup.html' | relative_url }}"
}
```

thanks!

**Comment by RenaeCamp** [comment]
I think I got this one done, but I'm not able to verify if the links work.  

I realized while I was doing this that I had put the link to Donburi on the wrong row in my glassary table so it was linking from Don instead.  I updated the hjccc-glossary csv, hopefully that fixes that too.

**Comment by evanwill** [comment]
thanks, all the links seem to work. 

Note, only the `hjccc-glossary.csv` file is used now, you updated both `hjccc-glossary.csv` and `glossary.csv`, hopefully both with the same updates? 

To avoid confusion, I cleaned up the `_data` folder and moved stuff that isn't currently used into the `work/old-data` folder.

**Comment by RenaeCamp** [comment]
Yep, same updates. I didn't know if anything was pulling from the glossary.csv so, just in case, I updated both.
