### ISSUE TITLE
Descriptive content

### ISSUE THREAD

**Issue by evanwill** [uidaholib/HJCCC_source#18]
@RenaeCamp to finish fleshing out the site you might look at adding some descriptive text to the pages. If you look in `pages` folder, each of those markdown files becomes the main pages (as you know from editing the "about"). It might be helpful to have a bit of context for each so that users understand the data they are navigating / visualizing. For example, i put some text on the `timeline.md`--but it is just my concept of what the viz is doing, you might want to change that and flesh out. 

I would add a blurb to timeline.md, resources.md, forms.md, and subjects.md.

Also you might think about adding a section about your classification system / philosophy / how it was developed on the about page--or we could make a subpage of about with more detail about it.

thanks

**Comment by RenaeCamp** [comment]
@evanwill will do!  I've got about a paragraph on the classification system on the About page already but it's not called out. 

Out of curiosity, where is the home page, since it's not in the pages folder?

**Comment by evanwill** [comment]
The home page is `index.md` at the root level of the repository. 

It is a bit more complex to edit because it is built out of a bunch of includes. 

- on `index.md`, you can edit "featured-image:" which is the image in the jumbotron, and "featured-subjects:" which is a list of subjects that link to the browse page. However, any content you write here will just be ignored, because it isn't used in the layout.
- `_layouts/home-infographic.html` is where the page is pulled together, you can see all the other includes that are chunks of content pulled from `_includes/`

So you could mess around with those--or tell me ideas and I can flesh them out at some point, maybe next week.
