### ISSUE TITLE
header text size on mobile?

### ISSUE THREAD

**Issue by evanwill** [uidaholib/HJCCC_source#20]
Awesome index page redesign @RenaeCamp and @dcnb !

only question: on mobile the banner text takes up most of a screen, and doesn't all fit in the jumbotron on smaller screens (like 5"ers). This might be okay, but maybe text should be a size smaller?

**Comment by dcnb** [comment]
that's a good point, @evanwill.  Will definitely look at that. Also, do you think the nav bar should be on the home page? I also thought about adding just a menu button that would then expand into the nav bar .. 

We also need some new logs for digital and cdil to put on these. I will try and mess around before I go.
