### ISSUE TITLE
Text Edits from Reviewers

### ISSUE THREAD

**Issue by RenaeCamp** [uidaholib/HJCCC_source#29]
- [x] Add University of Idaho after AACC on About Page

- [x] Add University of Idaho after AACC on object prefered citations

- [x] Add English translations to Top Subjects on Home Page

- [x] Add info on Aizu Hongo teapots (AACC-2018-01 and AACC-99-123)

**Comment by RenaeCamp** [comment]
Hey @evanwill and/or @dcnb , I 'm done with the text edits from reviewers--I hope!  I don't see the website changing as I make my edits, so I wanted to make sure I was still working in the right spot.  
I didn't make any really big changes but there are a couple things I'm a little nervous I might have messed up.  I tried to add another teapot form to the tree and to the glossary.  Could you let me know if these changes came through okay?  Thanks!

**Comment by evanwill** [comment]
@RenaeCamp the site is on our library web server now, so the rebuild is a manual process-- I will take a look at the code and get it rebuilt Monday. Thank you!

**Comment by evanwill** [comment]
Your code looks all good! 

but unfortunately...

I just realized that back in June I messed up all the Japanese characters when pulling over Devin's version of the site (6b32d63ffe56fdcbb464650bc313b02b03b09902). Should not have trusted Devin I guess :sob: 

Can't believe we didn't notice... I will try to fix them...

**Comment by evanwill** [comment]
okay--- Japanese character issue is fixed I believe. Please give it a look over. 

The updates are deployed on the main web server.

**Comment by RenaeCamp** [comment]
Looks good!!  All the edits seem to have come over.  

Last question: can we make the links, or at least the links on the Glossary Page blue so that they are more obvious to click on?  I took a look at the glossary page source code... but I think it's a little above my skill level.

**Comment by evanwill** [comment]
looks great! 
I am going to start working on pulling some of these innovations into a general UI template and pages-collection.

**Comment by RenaeCamp** [comment]
Yep, looks really good!!  All the links look much more "inviting."

I did find one thing I must not have done right: I thought I added Aizu-Hongo to the search terms for the Samehada-Gusuri Teipotto (shark-skin glaze teapot) but it doesn't come up when I search for Aizu-Hongo.  Did this get lost in the transfer or did I put the search term in the wrong spot?

**Comment by evanwill** [comment]
@RenaeCamp you put the data in, but the Browse page was set up a bit differently and wasn't using the "subjects" field. I put "subjects" back in for search purposes, so it works now: https://www.lib.uidaho.edu/digital/hjccc/browse.html#Aizu-Hongo
