### ISSUE TITLE
Add background to About Page, add metadata citation?

### ISSUE THREAD

**Issue by RenaeCamp** [uidaholib/HJCCC_source#31]
Devin pointed out that I don't have any information on where the HJCCC project came from on the About Page and that I don't mention myself anywhere. 

- [x] Add additional background to About Page

- [x] Add suggested metadata citation to object pages?

**Comment by RenaeCamp** [comment]
@evanwill  I tweaked the About Page a little bit.  Would you mind pulling the changes over to the official site at your convenience? 

Also, would it be possible to add another citation to the "Source" card on each item page?  I was thinking it would make sense to add:
**Metadata Created By:**
Renae Campbell 2018

This could be autofilled from the object table, which has a metadata creator field.  I was going to append all the entries in this field to include the year 2018, but I saw that I would need to make a branch first.  Should I do this and try to add the info to the item cards, or is it just easier if I leave it alone on my end?  I don't want to be creating more work for you if it is simpler for you to do it the first time than it is to pull my changes over.  

Thanks!  I swear I'll stop making changes as soon as we get these last couple things done.

**Comment by dcnb** [comment]
I'm at work finishing up a couple things so I'll do it right now.

**Comment by dcnb** [comment]
I updated the site. I also added a paragraph at the top of the about page
with information about the people who worked on the site (with your full
name first, Renae(!) because it didn't appear elsewhere ...). If you'd like
to adjust that, feel free.

**Comment by RenaeCamp** [comment]
Thanks @dcnb and @evanwill.  Looks great!  I hadn't even realized my name wasn't on the about page... 

Have a good conference.  I'm done messing around with things (and will stop bugging you), so just let me know when the attribution statement has been added to the downloadable images and I will email everyone with the final version.
