### ISSUE TITLE
AACC identifier issue?

### ISSUE THREAD

**Issue by evanwill** [uidaholib/HJCCC_source#32]
@RenaeCamp when adding metadata to the AACC images, I just noticed that there is three sets of identifiers, starting with: 

- `AACC-`
- `ACC-`
- `CCC-`

Are the ACC and CCC correct or a metadata issue? I can fix it pretty easily if necessary. Thanks,

**Comment by RenaeCamp** [comment]
@evanwill The AACC has gone through several name changes in the last 30+ years.  It started as the Chinese Comparative Collection (CCC), then became the Asian Comparative Collection (ACC), and finally the Asian American Comparative Collection (AACC).  Those catalog numbers are correct; they are remnants of the name changes.  But good catch and thanks for checking!!

**Comment by evanwill** [comment]
Thanks, I think I remember asking you that before... all good then!
