### ISSUE TITLE
Remove "database" link to CONTENTdm?

### ISSUE THREAD

**Issue by evanwill** [uidaholib/HJCCC_source#33]
@dcnb and @RenaeCamp looking at the site I am wondering if we should remove links to CONTENTdm all together since the images and metadata on the main site are now much more up-to-date than CONTENTdm version. 

Currently we link to CDM on "database" in the nav and via the search box. 
We could replace "database" with link to data page (https://www.lib.uidaho.edu/digital/hjccc/data/ ) and the search with a Lunr search (I would have to work on setting that up nicer).

**Comment by dcnb** [comment]
That makes sense to me! We still need to work on better branding etc. for
digital initiatives too.

**Comment by RenaeCamp** [comment]
I'm fine with removing links to CONTENTdm.  Or even just getting rid of the database page but keeping a smaller link to it somewhere else... up to you guys.  
Speaking of branding, if it's alright with you, once I email the Burke/Air Force I'm gonna start announcing the page on some archy sites to see if I can generate any users...
