### ISSUE TITLE
"and and"

### ISSUE THREAD

**Issue by evanwill** [uidaholib/HJCCC_source#4]
5 items have catalog number with "and and", is this an issue?

what is relation between catalog number and identifier, can we reduce identifier to a single value?

**Comment by RenaeCamp** [comment]
"and and" sounds like an issue. not sure how that happened but I will take a look.  

Catalog number is the unique identifier for each artifact.  It looks like identifier is a unique name for each view of each artifact.  So, for artifacts with only one photo they are the same but for artifacts with more than one photo they will be slightly different.  From an archaeological standpoint it is important to keep the catalog number in the metadata for each artifact, so we should probably keep both?

**Comment by evanwill** [comment]
fixed "and and" in CDM, and in this repository with 7de52c1ee3959098a52c64fda09a409904e311f1

additionally fixed identifier field issues-- should be good now!
