### ISSUE TITLE
Get images 

### ISSUE THREAD

**Issue by evanwill** [uidaholib/HJCCC_source#8]
- [x] make thumbs
- [x] sm display
- [x] full sized? (avoid CDM?)

**Comment by evanwill** [comment]
see `work/image-processing.md`.

full = 6000px, thumb = 300px, small = 800px

pushed to main web `/digital/hjccc/objects`

**Comment by evanwill** [comment]
never mind, got to do again-- some serious data anomalies because i used the original images, where the filenames were messed up, which was fixed in CDM, so doesn't match the metadata.

**Comment by evanwill** [comment]
grabbed the images from CONTENTdm, which are around 2000px long side, since I can then fix the filenames easily to match our metadata. 

all images are in `/digital/hjccc/objects`, small are `_sm.jpg` 600px, thumbs are `_th.jpg` 300px

I think this will work for now, although I would like to see higher pixel images--but probably not a priority right now

**Comment by evanwill** [comment]
browse and item pages are set to get images from the server, not CONTENTdm, so I am closing this. 
@RenaeCamp and @dcnb let me know if you think it is worth working on the original imagery to get larger images for download, at some point.

**Comment by dcnb** [comment]
I think the item pages look great, Evan. Good work!

Renae, you won't be able to see them unless you run it locally on your computer. I'll put it up somewhere though and send you the link for browsing.
