### ISSUE TITLE
timeline viz

### ISSUE THREAD

**Issue by evanwill** [uidaholib/HJCCC_source#9]
how to represent overlapping eras of manufacture

**Comment by RenaeCamp** [comment]
Maybe the artifact photos could go into "phase" boxes that run parallel the timeline, sort of like this
[Microsoft template](https://www.officetimeline.com/timeline-template/sales-plan-download), with discrete technology changes tied to specific dates (like the milestones in this example)?

**Comment by evanwill** [comment]
https://uidaholib.github.io/HJCCC_source/timeline/

@RenaeCamp and @dcnb I just quickly implemented our normal timeline with each era represented, and any object that has the era mentioned in the "manufacture-range" field has a thumb in the era. Hovering over the thumb gives you the title and full "manufacture-range" info. clicking brings you to the item page (this doesn't work on the gh-pages version, since it isn't generating the pages).

not what you were imagining at all... but kind of works?

**Comment by dcnb** [comment]
I like this a good deal. Site is looking strong!!!

Good work Evan and Renae. Let's do some work to spiff up the look a bit
this week.

**Comment by RenaeCamp** [comment]
I like this too!  The hover-over date is a great addition.  

I wonder if it would be cleaner to drop the artifacts that are from more than two eras (any that say "Meiji (1868-1912) through early Showa (1926-1989) eras") so there aren't so many repeating artifacts.

**Comment by evanwill** [comment]
Currently the time line is based on pretty fuzzy searching. Basically the values in "manufacture-range" are very diverse, so to generate the timeline i set the four eras (`eras = "Tokugawa (1603-1868);Meiji (1868-1912);Taisho (1912-1926);Showa (1926-1989)"`). Then in each era section, i search the "manufacture-range" field, and add any item that contains that era string (e.g. "Meiji (1868-1912)" is contained in four different facet values, so all those items are added). You will notice that several of the "manufacture-range" don't include any of the "era" strings, so won't be included anywhere in the timeline.

Here is what the facets look like right now in "hjccc-objects.csv", "manufacture-range": 

```
"likely taisho (1912-1926) through pre-wwii showa (1926-1942) era",3
"meiji (1868-1912) through early showa (1926-1989) eras",9
"meiji (1868-1912) through showa (1926-1989) eras",8
"mid-meiji through early showa eras (1889-1945)",1
"minimalistic hand-painted sometsuke may indicate taisho-era (1912-1926) manufacture",7
"most popular during the meiji (1868-1912) era",6
"most popular during the tokugawa (1603-1868) or early meiji (1868-1912) eras",1
"most popular in the late taisho (1912-1926) and early showa (1926-1989) eras",2
"most popular in the meiji (1868-1912) and taisho (1912-1926) eras",10
"most popular in the taisho (1912-1926) and early showa (1926-1989) eras",1
"most popular taisho (1912-1926) through very early showa (1926-1989) era",1
"the dominantly green transferprint may indicate manufacture during or shortly after the taisho era (1912-1926)",1
```

With the current data I can't really make it more precise without adding a bunch of custom exceptions.

@RenaeCamp could you make a new metadata field in "hjccc-objects.csv" based on "manufacture-range", called "timeline-era", that includes a normalized era value for the items you want to include? You could use more divisions than the four eras I set up, but I wouldn't make it too specific, since you want several representative examples in each division to be helpful. For items that you do NOT want on the timeline, just leave the value blank. 

I will then be able to rebuild the timeline based on your "timeline-era" column, it will include sections for each of the facets in the column.

**Comment by RenaeCamp** [comment]
Okay!  I added te timeline-era column and the following date options: Tokugawa (1603-1868);Early Meiji (1868-1885);Middle Meiji (1885-1895);Late Meiji (1895-1912);Taisho (1912-1926);Showa (1926-1989).
I also dropped 16 of the objects that aren't even loosely datable.

**Comment by evanwill** [comment]
Got it updated to use your new data--looks good. thanks.
